image: continuumio/miniconda3:latest
testsuite:
  script:
    - apt-get update -q -y
    - apt-get install -y build-essential wget
    - mkdir ~/.taxonkit && pushd ~/.taxonkit && wget ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz && tar -xzf taxdump.tar.gz && popd
    - conda env create -f environment.yaml
    - source activate pytaxonkit
    - make test
    - make style
