name: CI Build

on:
  push:
  schedule:
    - cron: '0 4 1 * *'

jobs:
  build:
    name: PyTaxonKit Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.6
          - os: ubuntu-latest
            python-version: 3.7
          - os: ubuntu-latest
            python-version: 3.8
          - os: macos-latest
            python-version: 3.7
    steps:
      - uses: actions/checkout@v1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yaml
          activate-environment: pytaxonkit
      - name: Taxonomy data download
        run: |
          mkdir ~/.taxonkit
          pushd ~/.taxonkit
          wget ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz
          tar -xzf taxdump.tar.gz
          popd
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .
          make devenv
      - name: Style check
        run: |
          make style
      - name: Test with pytest
        run: |
          make test
